### ISSUE TITLE
Version of the packages

### ISSUE THREAD

**Issue by Bturan19** [nandahkrishna/StockTrading#2]
Hello, firstly thanks for these notebooks. The code is clean and simple. I tried to make it work in my system but probably due to versions of tha packages I couldnt be able to work it. 

Can you add a requirements file?

**Comment by khadijabennouna** [comment]
@Bturan19 me too  i have the some probleme the versions of packages are not compatible to the code so it couldnt work. 
i hope that can you add a requirements file?

**Comment by Bturan19** [comment]
@khadijabennouna I'm sorry. I just moved on :)

**Comment by nandahkrishna** [comment]
Sorry for missing this. It's been a while since I worked on this project so I'm not aware what the exact versions were. I'll try to add a `requirements.txt`, but it's worth noting that a lot of changes have happened since I worked on this (for example, using `tensorflow.keras` instead of just `keras`).
